version: '3.4'

services:
  keycloakdb:
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DDB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    command: start --optimized
    ports:
      - 8080:8080
    environment:
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}