version: '3.4'

services:
  caddy:
    build:
      context: ./caddy
    container_name: keycloak_proxy
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}

    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  keycloakdb:
    container_name: keycloak_db
    image: postgres:${POSTGRES_VERSION:-14.5}-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-p@ssw0rd}

  keycloak:
    build:
      context: ./keycloak
    container_name: keycloak
    image: keycloak_image
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HTTP_ENABLED: "true"
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8443
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/${POSTGRES_DB:-keycloak}?useSSL=false
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-p@ssw0rd}
      KC_PROXY: edge
    # volumes:
    #   - ./keycloak/themes/custom:/opt/keycloak/themes/custom
    depends_on:
      - keycloakdb

volumes:
  caddy_data:
  caddy_config:
  pgdata:
